# Generated by Django 4.0.4 on 2022-05-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
