# Generated by Django 4.0.4 on 2022-05-13 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bridgeapp.thread'),
            preserve_default=False,
        ),
    ]
