# Generated by Django 4.0.4 on 2022-05-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeapp', '0003_response_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
