# Generated by Django 4.0.4 on 2022-06-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeapp', '0003_response_user_thread_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='body',
            field=models.TextField(),
        ),
    ]
