# Generated by Django 4.0.4 on 2022-05-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeapp', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='body',
            field=models.TextField(default='placeholder', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='body',
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
